# Generated by Django 4.1 on 2022-08-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_arcticletag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcticletag',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
